# Generated by Django 2.2.5 on 2019-12-22 05:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SavedGit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=500)),
                ('star', models.DecimalField(decimal_places=0, max_digits=1)),
                ('avtar', models.ImageField(upload_to='templates')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
